apiVersion: configme.javaworm.com/v1
kind: ConfigSource
metadata:
  name: simple-http-config
spec:
  sourceType: http
  targetConfigMapName: http-config
  sourceConfig: 
    url: https://jsonplaceholder.typicode.com/todos
    intervalSeconds: 10
