apiVersion: configme.javaworm.com/v1
kind: ConfigSource
metadata:
  name: simple-http-config
spec:
  sourceType: http
  targetConfigMapName: http-config
  sourceConfig: 
    url: https://opentable.herokuapp.com/api/cities
    intervalSeconds: 10
